### ISSUE TITLE
Problem with translating

### ISSUE THREAD

**Issue by Jason505** [AddstarMC/Minigames#149]
Hi there!
I was translating plugin for our server and every time, when I want to turn on plugin, it'll display some stupid errors such as:
```
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 78, column 26:
      livesLeft: Zbyva zivotu: %s'
                             ^
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        ... 17 more

```
```
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning an anchor
 in 'string', line 29, column 18:
        deathRevert: &cSmula. Vracim k checkpointu...
                     ^
expected alphabetic or numeric character, but found .(46)
 in 'string', line 29, column 25:
        deathRevert: &cSmula. Vracim k checkpointu...
                            ^
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1453) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAnchor(ScannerImpl.java:939) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:370) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:424) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[spigot.jar:git-Spigot-93e20b3-9ab758c]
        ... 17 more
```

It's strange, mainly that first error, because that colon is in the original language file too...
Any idea where is the mistake?

Thanks,
Jason505

**Comment by Narimm** [comment]
You need to use " " around each message.
ie   
 deathRevert: **"**Bad luck! Returning to checkpoint.**"**

**Comment by Narimm** [comment]
Oh if you finish the translation feel free to PR it back
