### ISSUE TITLE
EventException/NullPointerExeption on Minigame_Timer + Minigame_Timer_Condition

### ISSUE THREAD

**Issue by Turidus** [AddstarMC/Minigames#155]
To reproduce using  1.12.0 Minigames, 1.12 Regions and 1.12.2 Craftbukkit (Sep. 18 2017)

Create a minigame. Set that MG to multiplayer (the error does not occur in singleplayer). 
Create a node and give it a Minigame_Timer_Executer. 
Also add a Minigame_Timer condition.
Add an action (i used Minigame/SendMessageAction)

The moment the minigame starts (no matter if the condition resolves to true or false) following exeption does get thrown:
[01:09:09] [Server thread/ERROR]: Could not pass event MinigameTimerTickEvent to Minigames-Regions v${plugin.version}
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at au.com.mineauz.minigames.MinigameTimer$1.run(MinigameTimer.java:76) [Minigames-1.12.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]

Caused by: java.lang.NullPointerException
	at au.com.mineauz.minigamesregions.conditions.MinigameTimerCondition.checkNodeCondition(MinigameTimerCondition.java:56) ~[?:?]
	at au.com.mineauz.minigamesregions.Node.checkConditions(Node.java:95) ~[?:?]
	at au.com.mineauz.minigamesregions.Node.execute(Node.java:84) ~[?:?]
	at au.com.mineauz.minigamesregions.RegionEvents.minigameTimerTick(RegionEvents.java:346) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-82f3b02]
	... 11

[latest.log](https://github.com/AddstarMC/Minigames/files/1519975/latest.log)

The action does not execute (see Issue #156 ).

**Comment by Narimm** [comment]
I would ask you update to the latest stable build and recheck for the error.

**Comment by Turidus** [comment]
I made a clean install of the newest craftbukkit and the Minigames Pack v1.12.0-SNAPSHOT-216
(Latest build available on https://www.spigotmc.org/resources/minigames.19687/)

Minigames Region behaved in the exact same way, with no execution of the Minigame_Tick trigger and the error with the additional condition.

To be sure i did the same thing with the newest dev build v1.12.1-SNAPSHOT-224 (http://jenkins.addstar.com.au/job/Minigames/lastBuild/)

Here the condition did NOT lead to an error!
