### ISSUE TITLE
java.sql.SQLException: The prepared statement has been finalized

### ISSUE THREAD

**Issue by AfkF24** [AddstarMC/Minigames#194]
Getting the following warning when shutting down the server:
```
[13:39:51 INFO]: [Minigames] Disabling Minigames v1.12.2-RC-258
[13:39:52 WARN]: java.sql.SQLException: The prepared statement has been finalized
[13:39:52 WARN]: at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
[13:39:52 WARN]: at org.sqlite.core.NativeDB.finalize(Native Method)
[13:39:52 WARN]: at org.sqlite.core.DB.exec(DB.java:159)
[13:39:52 WARN]: at org.sqlite.jdbc3.JDBC3Connection.setAutoCommit(JDBC3Connection.java:164)
[13:39:52 WARN]: at au.com.mineauz.minigames.backend.ConnectionHandler.endTransaction(ConnectionHandler.java:144)
[13:39:52 WARN]: at au.com.mineauz.minigames.backend.sqlite.SQLiteBackend.saveStatSettings(SQLiteBackend.java:303)
[13:39:52 WARN]: at au.com.mineauz.minigames.backend.BackendManager$8.call(BackendManager.java:223)
[13:39:52 WARN]: at au.com.mineauz.minigames.backend.BackendManager$8.call(BackendManager.java:220)
[13:39:52 WARN]: at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
[13:39:52 WARN]: at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
[13:39:52 WARN]: at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
[13:39:52 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:39:52 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:39:52 WARN]: at java.lang.Thread.run(Thread.java:748)
```
* **Please tell us about your environment:**
- Spigot Version: Paper 1.12.2- build 1533
- Minigames version: 1.12.1- build 258

**Comment by Narimm** [comment]
Thanks for the report the warning isnt concerning...we were attempting to clear a transaction 2 ways...I have now implemented a fix that I will commit shortly.
