### ISSUE TITLE
"The configuration file may be corrupt or missing!" On Start.

### ISSUE THREAD

**Issue by SebSeifert** [AddstarMC/Minigames#198]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
It's a bug.

* **What is the current behavior?**
On the start on the Server I have the Log full of errors like:
`[00:32:28] [Server thread/ERROR]: [Minigames] §cFailed to load "Mario_CTF"! The configuration file may be corrupt or missing!
[00:32:28] [Server thread/WARN]: java.lang.NullPointerException
[00:32:28] [Server thread/WARN]:        at au.com.mineauz.minigames.minigame.reward.RewardsModule.load(RewardsModule.java:75)
[00:32:28] [Server thread/WARN]:        at au.com.mineauz.minigames.minigame.Minigame.loadMinigame(Minigame.java:1268)
[00:32:28] [Server thread/WARN]:        at au.com.mineauz.minigames.Minigames$1.run(Minigames.java:107)
[00:32:28] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[00:32:28] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[00:32:28] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[00:32:28] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[00:32:28] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[00:32:28] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[00:32:28] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)`

In Some cases it's right and the config.yml of this minigame is empty. But on others not.
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Spigot Version: 1.12
- Minigames version: 1.12.1- build #

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
copy out the config and let the plugin recreate that config   - then copy back in your settings using vim or another editor.

**Comment by Narimm** [comment]
Give the lack of update I am going to close this for  now please reopen if you can provide a valid config that causes the issue
