### ISSUE TITLE
Minigames 1.13.1 Dev build (17/02/19)

### ISSUE THREAD

**Issue by Rouchesta** [AddstarMC/Minigames#210]
Dear Dev,

* **I'm submitting a ... **
  - [ ] bug report

* **What is the current behavior?**
Internal error on all Minigames commands.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
Typing commands, plugin don't work.

* **What is the expected behavior?**
Working Minigames

* **Please tell us about your environment:**
- Spigot Version:  Paper 1.13.2
- Minigames version: 1.13.1- DevBuild #

Error code : 
`
[23:42:22 ERROR]: Could not pass event PlayerInteractEvent to Minigames v1.13.1-SNAPSHOT-295
org.bukkit.event.EventException: null
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[Paper-1.13.2.jar:git-Paper-521]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper-1.13.2.jar:git-Paper-521]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-1.13.2.jar:git-Paper-521]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper-1.13.2.jar:git-Paper-521]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[Paper-1.13.2.jar:git-Paper-521]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[Paper-1.13.2.jar:git-Paper-521]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[Paper-1.13.2.jar:git-Paper-521]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at au.com.mineauz.minigames.managers.MinigamePlayerManager.joinMinigame(MinigamePlayerManager.java:74) ~[?:?]
        at au.com.mineauz.minigames.signs.JoinSign.signUse(JoinSign.java:108) ~[?:?]
        at au.com.mineauz.minigames.signs.SignBase.signUse(SignBase.java:97) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[Paper-1.13.2.jar:git-Paper-521]
        ... 17 more
`

Thank you for the help.

**Comment by Narimm** [comment]
This error should have been fixed in recent  builds if it isnt can you please repost a stack from the latest dev build because this one doesnt give me any information has it isnt up to date

**Comment by Rouchesta** [comment]
Hi Narimm,

Just tested with Paper 1.13.2 and Last Dev build found here : 
When i try to join a MGM with the sign or the command i get the following errors : 

`
[09:15:31] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Minigames v1.13.1-SNAPSHOT-295
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[Paper-1.13.2.jar:git-Paper-525]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper-1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper-1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1362) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[Paper-1.13.2.jar:git-Paper-525]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[Paper-1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at au.com.mineauz.minigames.managers.MinigamePlayerManager.joinMinigame(MinigamePlayerManager.java:74) ~[?:?]
	at au.com.mineauz.minigames.signs.JoinSign.signUse(JoinSign.java:108) ~[?:?]
	at au.com.mineauz.minigames.signs.SignBase.signUse(SignBase.java:97) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[Paper-1.13.2.jar:git-Paper-525]
	... 17 more
[09:15:36] [Server thread/INFO]: Rouchesta issued server command: /mgm join test1
[09:15:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mgm' in plugin Minigames v1.13.1-SNAPSHOT-295
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.13.2.jar:git-Paper-525]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Paper-1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[Paper-1.13.2.jar:git-Paper-525]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[Paper-1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[Paper-1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at au.com.mineauz.minigames.managers.MinigamePlayerManager.joinMinigame(MinigamePlayerManager.java:74) ~[?:?]
	at au.com.mineauz.minigames.commands.JoinCommand.onCommand(JoinCommand.java:62) ~[?:?]
	at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:177) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.13.2.jar:git-Paper-525]
	... 15 more
`

Thank you.
Gaëtan.

**Comment by Rouchesta** [comment]
Where can i find the build you are talking about ? Can't find between Jenkins, Github, Travis, Spigot, ...

**Comment by Narimm** [comment]
Sorry I dont neccessarily build every commit - you would need to do that
yourself

Ben Charlton
