### ISSUE TITLE
/mg create NAME not working

### ISSUE THREAD

**Issue by ThePenguinPrince** [AddstarMC/Minigames#237]
null
org.bukkit.command.CommandException: Unhandled exception executing command 'mg' in plugin Minigames v1.14-SNAPSHOT-305
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628) ~[craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1340) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1200) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_202]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit.jar:git-Bukkit-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit.jar:git-Bukkit-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NoSuchFieldError: WALL_TORCH
        at au.com.mineauz.minigames.blockRecorder.RecorderData.<clinit>(RecorderData.java:54) ~[?:?]
        at au.com.mineauz.minigames.minigame.Minigame.<init>(Minigame.java:153) ~[?:?]
        at au.com.mineauz.minigames.commands.CreateCommand.onCommand(CreateCommand.java:74) ~[?:?]
        at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:177) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-e60fc34]
        ... 15 more

**Comment by ThePenguinPrince** [comment]
I've tried using the latest build and the 1.12.2 version, too, with no positive results.
