### ISSUE TITLE
Minigame won't start with /mg start [game]

### ISSUE THREAD

**Issue by themindstorm** [AddstarMC/Minigames#241]
- [x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I created a game, so I want to test it with `/mg start [game]`. The countdown starts, but get stuck as `4sec`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

Here's what comes in the console:

```
[21:35:04 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:05 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:06 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:07 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:08 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:09 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:10 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:11 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[21:35:12 WARN]: [Minigames] Task #33 for Minigames v1.12.0-SNAPSHOT- generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
	at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

```

![image](https://user-images.githubusercontent.com/34677361/67398149-d237e700-f5dc-11e9-834d-553085577615.png)

* **What is the expected behavior?**
The game should start.

[There is only one player in the game, and I want to start the game. Could the problem be that I'm trying to force start the game with only one player? I already did `/mg set [game] minplayers 1`]

 **Please tell us about your environment:**
- Paper Version: 1.14.2
- Minigames version: 1.12.0 (downloaded from spigotmc). I can't download the newest one from the releases on GitHub because the file is not found

**Comment by Narimm** [comment]
That version doesnt support 1.14

**Comment by themindstorm** [comment]
Do any of the versions support 1.14? If no, will the plugin be updated to 1.14.

Also, I am unable to download the latest version of the plugin from the releases tab. It says HTTP 404 when I click this link: https://jenkins.addstar.com.au/job/Development_Builds/job/Minigame_Dev/53/au.com.mineauz$Minigames/artifact/au.com.mineauz/Minigames/1.12.2-SNAPSHOT/Minigames-1.12.2-SNAPSHOT.jar

**Comment by Narimm** [comment]
We have not updated to 1.14 yet ...its in the works
Development build for 1.14 is here
https://jenkins.addstar.com.au/job/Minigames/lastSuccessfulBuild/artifact/minigamesdistribution/target/
