### ISSUE TITLE
NPE on PlayerHasItem

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Minigames#252]
2019-12-16 20:10:32 [Server thread/WARN]: Task #172268 for Minigames v1.14-SNAPSHOT- generated an exception
java.lang.NullPointerException: null
        at au.com.mineauz.minigamesregions.conditions.PlayerHasItemCondition.check(PlayerHasItemCondition.java:133) ~[?:?]
        at au.com.mineauz.minigamesregions.conditions.PlayerHasItemCondition.checkRegionCondition(PlayerHasItemCondition.java:75) ~[?:?]
        at au.com.mineauz.minigamesregions.Region.checkConditions(Region.java:200) ~[?:?]
        at au.com.mineauz.minigamesregions.Region.execute(Region.java:189) ~[?:?]
        at au.com.mineauz.minigamesregions.Region.lambda$startTickTask$1(Region.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by MiniWorks18** [comment]
This bug has broken a few games. I did some testing, it looks like the condition works perfectly if either the namePattern or the lorePattern matches a custom name on the item. So, if my item is a stone block named "steve" and my condition is searching for a stone blocked named "steve", then it passes and works fine without any stack traces. 
If my condition is searching for a name but doesn't find it on the item, it will through the stack trace.  And if my condition is searching for no name and no lore, it still throws the stack.

So, it might be the if statement at line 152 
`                        if (lore.getFlag() != null) {
                            continue;
                        }`
Not entirely sure though, I'm not familiar with the code.

**Comment by Narimm** [comment]
This bug is no longer valid...because its an old version

**Comment by MiniWorks18** [comment]
Bugs don't fix themselves :P I can share an updated stack if you'd like? I can confirm it still happens in the latest build.
