### ISSUE TITLE
MG on 1.15.2 crashing on mg start

### ISSUE THREAD

**Issue by AeSix** [AddstarMC/Minigames#275]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
crashing / error in console

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
created a minigame in which a wither is spawned on game start (player join trigger)

* **What is the expected behavior?**
a wither spawn and the server not crash

* **What is the motivation / use case for changing the behavior?**
make minigames actually work like it's intended?

* **Please tell us about your environment:**
- Spigot Version:
```This server is running CraftBukkit version git-Spigot-2040c4c-94cb030 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```  (I am admittedly 3 versions behind, however, if my staff had finished the arena 2-3 days ago, I would not be, however, I would be using the same build of MiniGames)
- Minigames version:
```
[06:20:43] [Server thread/INFO]: Minigames version 1.15-SNAPSHOT-316
[06:20:43] [Server thread/INFO]: A swiss knife plugin to construct any minigame you can imagine.
[06:20:43] [Server thread/INFO]: Author: _Razz_ Schmoller Addstar Narimm
```



* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
[06:11:17] [Async Chat Thread - #1/ERROR]: Could not pass event AsyncPlayerChatEvent to Minigames v1.15-SNAPSHOT-316
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1580) [spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1518) [spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1110) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1096) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:348) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:333) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        at au.com.mineauz.minigames.menu.Menu.displayMenu(Menu.java:160) ~[?:?]
        at au.com.mineauz.minigames.menu.MenuItemString.checkValidEntry(MenuItemString.java:82) ~[?:?]
        at au.com.mineauz.minigames.Events.manualItemEntry(Events.java:721) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-server.jar:git-Spigot-2040c4c-94cb030]
        ... 11 more
```

**Comment by Narimm** [comment]
I am confused that error is from someone trying to edit a string flag in a minigame ..not start a minigame

**Comment by AeSix** [comment]
The error occurred when my staff would enable the minigame and attempt to join it. 

With buil 316 and now 318, when joining the minigame, the server quits.  

More specifically:
/mg join wither 
I am teleported to starting location
countdown timer ticks
mg starts
another countdown starts, and I am given the mg reward
3 seconds later, the server stops (somewhat graceful shutdown of Spigot)


Even if the minigame is ill-configured, the plugin should handle it better than to stop the server.

**Comment by AeSix** [comment]
the other minigame we have does not crash the server. It is not player-join triggered however.

**Comment by Narimm** [comment]
You will need to post the shutdown message

**Comment by FireInstall** [comment]
Pretty sure the bug of the stack trace is fixed.
