### ISSUE TITLE
teams not creating - error details provided

### ISSUE THREAD

**Issue by sudocode1** [AddstarMC/Minigames#277]
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
teams are not creating, giving error in console

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
[ERROR] Could not pass event AsyncPlayerChatEvent to Minigames v1.7.0

org.bukkit.event.EventException

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1649.jar:git-PaperSpigot-43]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1649.jar:git-PaperSpigot-43]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot1649.jar:git-PaperSpigot-43]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491) [spigot1649.jar:git-PaperSpigot-43]

at net.minecraft.server.v1_7_R4.PlayerConnection.chat(PlayerConnection.java:966) [spigot1649.jar:git-PaperSpigot-43]

at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:906) [spigot1649.jar:git-PaperSpigot-43]

at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot1649.jar:git-PaperSpigot-43]

at net.minecraft.server.v1_7_R4.PacketPlayInChat$1.run(PacketPlayInChat.java:59) [spigot1649.jar:git-PaperSpigot-43]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoClassDefFoundError: org.bukkit.scoreboard.NameTagVisibility

at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:104) ~[?:?]

at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:99) ~[?:?]

at au.com.mineauz.minigames.menu.MenuItemAddTeam.checkValidEntry(MenuItemAddTeam.java:49) ~[?:?]

at au.com.mineauz.minigames.Events.manualItemEntry(Events.java:649) ~[?:?]

at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot1649.jar:git-PaperSpigot-43]

... 12 more

Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.NameTagVisibility

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot1649.jar:git-PaperSpigot-43]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1649.jar:git-PaperSpigot-43]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]

at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:104) ~[?:?]

at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:99) ~[?:?]

at au.com.mineauz.minigames.menu.MenuItemAddTeam.checkValidEntry(MenuItemAddTeam.java:49) ~[?:?]

at au.com.mineauz.minigames.Events.manualItemEntry(Events.java:649) ~[?:?]

at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot1649.jar:git-PaperSpigot-43]

... 12 more

is the error when i try to type in a team name

* **What is the expected behavior?**
create team

* **What is the motivation / use case for changing the behavior?**
???

* **Please tell us about your environment:**
- Spigot Version: unsure
- Minigames version: 1.7 latest build

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment]
Unfortunately we no longer support 1.7
