### ISSUE TITLE
Can't add teams Build 133

### ISSUE THREAD

**Issue by prodkid** [AddstarMC/Minigames#33]
When I try to add a team here what occurs
[11:55:18] [Netty IO #2/ERROR]: Could not pass event AsyncPlayerChatEvent to Minigames v1.7.0-b133
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1230) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1155) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:137) [ej.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:351) [ej.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:193) [NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:43) [NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/scoreboard/NameTagVisibility
	at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:104) ~[?:?]
	at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:99) ~[?:?]
	at au.com.mineauz.minigames.menu.MenuItemAddTeam.checkValidEntry(MenuItemAddTeam.java:49) ~[?:?]
	at au.com.mineauz.minigames.Events.manualItemEntry(Events.java:649) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	... 36 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.NameTagVisibility
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:394) ~[PluginClassLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_75]
	at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:104) ~[?:?]
	at au.com.mineauz.minigames.minigame.modules.TeamsModule.addTeam(TeamsModule.java:99) ~[?:?]
	at au.com.mineauz.minigames.menu.MenuItemAddTeam.checkValidEntry(MenuItemAddTeam.java:49) ~[?:?]
	at au.com.mineauz.minigames.Events.manualItemEntry(Events.java:649) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	... 36 more

**Comment by addstar** [comment]
Closing old unhandled issues, re-open if you still have an issue.
