### ISSUE TITLE
Minigames 1.9

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Minigames#43]
Oi! Its me again, didn't noticed you had it in your github, it were by Razz I guess but whatever... 

I tested it and it work on "Single Player" mode, but when 2 players joins , the countdown stops at 10 and spam alot the console that couldn't init sounds. 

On SP games, it throws an error while finishing the game.

I've found this link from the minigames's bukkit page, I guess the author added it

**Comment by Sharrq** [comment]
Im seeing the same issue on the latest spigot version. You can create arenas and set everything up, you can join the arena, but when the arena starts and starts doing the countdown it gets stuck and does the same number repeatedly (for me its 4 over and over again because i lowered the countdown to 5 seconds). The console has a ton of errors regarding sound effects (ill post the error when i get home). I tried turning off sounds in the config to try and get around the issue, but it still did the same thing. 

Please update to 1.9, we love this plugin and would really hate to have to replace it.

**Comment by TNTUP** [comment]
@Sharrq I did fork and did fixes (they was easy and I used google ;-;) and it work, but I'm not recommending to use mine since Addstar can fix it officially. I removed the dragonegg code earlier but didn't bother pushing in my repo. Guess I'm not allowed to release it, idk

**Comment by Sharrq** [comment]
@TNTUP If you wouldnt mind sending that to me, I would be grateful. I could potentially use that until addstar fixes it and releases it. Im not a programmer so id rather not monkey around trying to fix it myself :)

**Comment by TNTUP** [comment]
@Sharrq I'm not responsible if you use my build that could contain bugs/errors or it could altering your games because I haven't tested all games I have setup (Tried Skywars Multi and it works)

**Comment by Sharrq** [comment]
@tntup I understand. I have backups of everything and would be testing this on an isolated test server before putting it anywhere near my production server, so im ok with that.

**Comment by addstar** [comment]
We will be working on updating this to 1.9 very soon, it's critical for our server and still heavily used with most of our games. Hopefully we can get to it sometime this week.

And yes, Minigames was created by Razz, but he's decided to hand the project over to us. He no longer has the time/interest to maintain it and we've known him for a long time (he is even part of our server admin team). I can assure you that we use this plugin heavily on our servers and have no intention of letting it die :grin:

**Comment by TNTUP** [comment]
Sweet :D Temporaily I did a temp fix for myself and it works^^

**Comment by Sharrq** [comment]
Thanks for the update! We can survive without it for a few weeks, ill just wait for the official update :)

**Comment by addstar** [comment]
You can find an initial 1.9 compatibility dev build here:
http://jenkins.addstar.com.au/job/Minigames/163/

Be aware, this is untested and it only has the minimal changes to make it run on 1.9. It's very likely there will be behaviour or game mechanic differences that could break things. Please report any errors or changes in behaviour so we can fix them up :smile:

**Comment by TNTUP** [comment]
Hey Addstar, while stopping the server, it throws error about sqlite misuse, can this safely ignored? I don't want inventory issues while the server stops/crashs etc.

[15:16:11] [Server thread/INFO]: [Minigames] Disabling Minigames v1.9.0.165
[15:16:11] [Server thread/INFO]: Minigames successfully disabled.
[15:16:12] [pool-70-thread-1/WARN]: java.sql.SQLException: [SQLITE_MISUSE]  Library used incorrectly (out of memory)
[15:16:12] [pool-70-thread-1/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[15:16:12] [pool-70-thread-1/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[15:16:12] [pool-70-thread-1/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[15:16:12] [pool-70-thread-1/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[15:16:12] [pool-70-thread-1/WARN]: 	at org.sqlite.DB.exec(DB.java:68)
[15:16:12] [pool-70-thread-1/WARN]: 	at org.sqlite.Conn.setAutoCommit(Conn.java:336)
[15:16:12] [pool-70-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.ConnectionHandler.endTransaction(ConnectionHandler.java:144)
[15:16:12] [pool-70-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.sqlite.SQLiteBackend.saveStatSettings(SQLiteBackend.java:260)
[15:16:12] [pool-70-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.BackendManager$8.call(BackendManager.java:225)
[15:16:12] [pool-70-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.BackendManager$8.call(BackendManager.java:222)
[15:16:12] [pool-70-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:16:12] [pool-70-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:16:12] [pool-70-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:16:12] [pool-70-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by addstar** [comment]
Unfortunately we haven't tested SQLite for a long time, we use mysql for our database storage.. and we also don't currently use 1.9 minigames in our server yet (it was only built for testing). When we start testing it further, I'll try to do some SQLite testing too.

I can't tell you if that is going to cause any issues, it looks like it's only failing to save stats. So there's a possibility your stats will not be accurate.

However, doing a quick google search on that particular SQLException points towards a bug in the SQLite library. So we'll look into this too, but unfortunately you'll have to wait for us to begin our proper 1.9 testing.
