### ISSUE TITLE
PlayerInteractEvent error

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Minigames#46]
Hi, testing the minigames plugin and I got this error:

[23:17:40 ERROR]: Could not pass event PlayerInteractEvent to Minigames v1.9.0.165
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
        at au.com.mineauz.minigames.Events.playerInterract(Events.java:269) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
        ... 17 more

Will use this build on my 1.9.2 server, due today to update (April 10)

**Comment by TNTUP** [comment]
EDIT: there's a new error which worked with my "fix" but reusing yours works, idk when i update the server the issue persists

[03:27:27] [Server thread/ERROR]: [Minigames] §cFailed to load "SkyWars01"! The configuration file may be corrupt or missing!
[03:27:27] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.placeRootSign(ScoreboardDisplay.java:343)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.updateSigns(ScoreboardDisplay.java:172)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.ScoreboardData.refreshDisplays(ScoreboardData.java:57)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.Minigame.saveMinigame(Minigame.java:1260)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.Minigame.loadMinigame(Minigame.java:1364)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.Minigames$1.run(Minigames.java:117)
[03:27:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[03:27:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[03:27:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[03:27:27] [Server thread/ERROR]: [Minigames] §cFailed to load "skywars04"! The configuration file may be corrupt or missing!
[03:27:27] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.placeRootSign(ScoreboardDisplay.java:343)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.updateSigns(ScoreboardDisplay.java:172)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.ScoreboardData.refreshDisplays(ScoreboardData.java:57)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.Minigame.saveMinigame(Minigame.java:1260)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.minigame.Minigame.loadMinigame(Minigame.java:1364)
[03:27:27] [Server thread/WARN]: 	at au.com.mineauz.minigames.Minigames$1.run(Minigames.java:117)
[03:27:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[03:27:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[03:27:27] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[03:27:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

[03:27:30] [Server thread/WARN]: [Minigames] Task #1596 for Minigames v1.9.0.165 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.placeRootSign(ScoreboardDisplay.java:343) ~[?:?]
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.updateSigns(ScoreboardDisplay.java:172) ~[?:?]
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay$4.onSuccess(ScoreboardDisplay.java:453) ~[?:?]
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay$4.onSuccess(ScoreboardDisplay.java:448) ~[?:?]
	at com.google.common.util.concurrent.Futures$5.run(Futures.java:1231) ~[spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[03:27:30] [Server thread/WARN]: [Minigames] Task #1598 for Minigames v1.9.0.165 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.placeRootSign(ScoreboardDisplay.java:343) ~[?:?]
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay.updateSigns(ScoreboardDisplay.java:172) ~[?:?]
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay$4.onSuccess(ScoreboardDisplay.java:453) ~[?:?]
	at au.com.mineauz.minigames.minigame.ScoreboardDisplay$4.onSuccess(ScoreboardDisplay.java:448) ~[?:?]
	at com.google.common.util.concurrent.Futures$5.run(Futures.java:1231) ~[spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-1e2fcb3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Murreey** [comment]
We had this too on updating to 1.9 - go into that Minigame's config.yml file, then remove the Scoreboards listed. Restart the server, and then add the scoreboards back again. That'll fix the second issue at least.

**Comment by TNTUP** [comment]
@Murreey Thanks for the tip! Though other minigames doesn't have the scoreboard thing enabled, I see "scoreboard: {}" but those ones which errored has it enabled something like 

scoreboard:
__'0':
____<etc>

**Comment by Narimm** [comment]
Different version use different configurations make sure you review change logs when updating to see if there are config changes
