### ISSUE TITLE
Problem & Suggestion

### ISSUE THREAD

**Issue by KilledCJ44** [AddstarMC/Minigames#49]
Hello,
I vien by this post to inform you of beugs and suggestion:

Beugs:
- Problem random chest, my server crashes when I activate this option on your plugin. 
  I think it has to generate all the chests of the entire map. Only I want that part of the map for my mini-games.
- Sometimes after creating a mini-game called X, it duplicates itself and create a second (X²), when I try to configure X configures me X² priority and this is quite annoying knowing that I must remove the two and recreate another ... 
  PS: I have to check in the file / root / server / plugins / Minigames / minigames / ... if there was no copy of X calling X² and I did not find ... 
  I hope you understand me is a bit of gibberish;)
- When the map of regeneration is activated and this regeneration takes a fairly large area that makes my server crash ...
- Problem of pvp. I create a mini game in team such as a flag and capture it is that players from the same team can beat them. 
  In some games it does not happen but it's a problem for me ... 
  I just find it hard to set the games.
- Problem with the sign. It turns out that when I use a sign for my choosing red or blue team in the lobby mini games it's killing me directly ... 
  It is quite irritating to die directly after click. 
  Then his told me as what I am no longer in the game while I was teleport spawn point for my team. 
  I noticed her when I use / mgm quit ... 
  Its like told me what I can not use this command because I am in any part.

Suggestion:
- Set a loadout the mini-games lobby to allow players to have items in case the person would leave the games instead of using sign (With commands given to items). 
  On the other hand I would allow the players to choose their loadout in the same way as clicking each time on his devien irritating sign ... 
  If possible her would be more clean and simple players.
- Allow the administrator to change the name "Minigames" in "Mini-Jeux" because I am French and I would like this to be configurable in the file 'config.yml'
- To allow the plugin to create several 'FloorDegenerator' because I would have wanted to create a The Walls with several wall that disappears after a certain time.
- Ensure that in areas we can create a timing before an action is performed ... 
  Let me explain: I wanted to create a pvpswap and after some time the player will be teleported into another arena, possess it stun the effect as in true pvpswap before teleportation so on ... 
  These actions will execute the will with precise timing before the action is launched. On the other hand I would also send global message after a while to inform players of an event like the fallen kindom. 
  Example: /broadcast Day 1, Night 1, Day 2, Night 2 ect ...
- Set a spawn point for each team in the lobby. Its allows players to see who is in which team.
- Allow to choose his team before joining a game ... Example: /mgm join X red. His could offer more options to players without using sign.
# I mean yours has some people like to use sign for the mini-games but then preferred to use controls ...
# I use mostly the plugin "ChestCommands" for all that is command or "CustomJoinItems" to assign commands to the items ...
# Of course this strongly suits me to use commands in place of the sign ...
# I highly recommend to perform my suggestions as this little make it simpler and cleaner plugin.

Thanks :
For my share yours to congratulate and encourage you because I can assure you that your plugin worth it and I recommend it to all who look at this post because it really interresting plugin offers functionality and complete ... 
Not bad these feature must be supported by several plugin simultaneously while this plugin is all in one ...
The possibility of creating mini games are huge ... I have a Minecraft server and I can assure you that there are games that you have never seen in the world of Minecraft if this plugin did not exist !
I encourage you to continue and if there are ways to make donations would love to help you with your work  and to encourage you ...

On the other hand I understand entirely if you can resourare some beugs or suggestion I offer you ... 
This is a puzzle for you and a big work !

PS: Sorry for my translation I'm not endow in English ;)

I shall send you my greeting friendly. Mr Charly JORDAN

**Comment by SlimeVortex** [comment]
[13:26:09 ERROR]: Could not pass event PlayerInteractEvent to Minigames v1.9.0.165
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
        at au.com.mineauz.minigames.signs.TeamSign.signUse(TeamSign.java:98) ~[?:?]
        at au.com.mineauz.minigames.signs.SignBase.signUse(SignBase.java:98) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-944aa20-8d16fc0]
        ... 17 more
[13:26:12 ERROR]: Could not pass event PlayerInteractEvent to Minigames v1.9.0.165
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot.jar:git-Spigot-944aa20-8d16fc0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
        at au.com.mineauz.minigames.signs.TeamSign.signUse(TeamSign.java:98) ~[?:?]
        at au.com.mineauz.minigames.signs.SignBase.signUse(SignBase.java:98) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-944aa20-8d16fc0]
        ... 17 more

**Comment by Narimm** [comment]
Closed as old issue....please try a the development versions and open a new issue
