### ISSUE TITLE
"[SQLITE_MISUSE]  Library used incorrectly (out of memory)" on server shutdown

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Minigames#56]
Hi, I don't know if this error should be "important" or it can be freely ignored? Lol why it says "Out Of memory" which the server has like 16Gb allocated?

[02:23:38] [Server thread/INFO]: [Minigames] Disabling Minigames v1.9.0.166
[02:23:38] [Server thread/INFO]: Minigames successfully disabled.
[02:23:41] [pool-71-thread-1/WARN]: java.sql.SQLException: [SQLITE_MISUSE]  Library used incorrectly (out of memory)
[02:23:41] [pool-71-thread-1/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[02:23:41] [pool-71-thread-1/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[02:23:41] [pool-71-thread-1/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[02:23:41] [pool-71-thread-1/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[02:23:41] [pool-71-thread-1/WARN]: 	at org.sqlite.DB.exec(DB.java:68)
[02:23:41] [pool-71-thread-1/WARN]: 	at org.sqlite.Conn.setAutoCommit(Conn.java:336)
[02:23:41] [pool-71-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.ConnectionHandler.endTransaction(ConnectionHandler.java:144)
[02:23:41] [pool-71-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.sqlite.SQLiteBackend.saveStatSettings(SQLiteBackend.java:260)
[02:23:41] [pool-71-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.BackendManager$8.call(BackendManager.java:225)
[02:23:41] [pool-71-thread-1/WARN]: 	at au.com.mineauz.minigames.backend.BackendManager$8.call(BackendManager.java:222)
[02:23:41] [pool-71-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:23:41] [pool-71-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[02:23:41] [pool-71-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[02:23:41] [pool-71-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by addstar** [comment]
I would definitely say that message is important and should not be ignored. The SQLite library thinks it is being used incorrectly. There is a good chance that you are losing stats data from Minigames. Unfortunately we only use Mysql on our own server so we have never experienced this error and it is difficult to troubleshoot.

Could you provide more information about when this occurred and does it happen frequently? Also, are you able to reproduce easily? We may be able to fix the bug but will need a lot of info and testing if you are willing. This looks like it's happening on server shutdown?

**Comment by TNTUP** [comment]
I don't care about minigame's stats xD It happens while the server is being shutdown

**Comment by addstar** [comment]
Ok, then in your case you can just ignore it :wink: 
If we do more work on SQLite in the future, this will get fixed.

**Comment by TNTUP** [comment]
Thanks :)
