### ISSUE TITLE
pls help me 

### ISSUE THREAD

**Issue by PetteRed65** [AddstarMC/Minigames#74]

**Comment by PetteRed65** [comment]
I have installed your plugin and created a CTF game.
When i go in the lobby for play, the timer keeps repeating 5sec, 5sec, 5sec until i return in the lobby.
In the console i get this:
[15:45:11 WARN]: [Minigames] Task #43 for Minigames v1.7.0 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class au.com.mineauz.minigames.sounds.MGSounds
        at au.com.mineauz.minigames.MultiplayerTimer$1.run(MultiplayerTimer.java:83) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by alchemistmatt** [comment]
See the comments for issue #73

Get the latest build from http://jenkins.addstar.com.au/job/Minigames/ and see also https://www.spigotmc.org/resources/minigames.19687/

**Comment by PetteRed65** [comment]
thanks.
I have installed the newest version an the timer bug has resolved.
I have found another:
when i start the game, the plugin forget to give me the gamemode 0, and i
can't touch sign and place block.

2017-01-04 21:58 GMT+01:00 Matthew Monroe <notifications@github.com>:

**Comment by alchemistmatt** [comment]
I'm not 100% sure, but I don't think the plugin supports auto-updating gamemode when you join a minigame -- you have to do that yourself or via some other means.

**Comment by PetteRed65** [comment]
i can't use commands from when i join the lobby

2017-01-04 22:50 GMT+01:00 Matthew Monroe <notifications@github.com>:

**Comment by PetteRed65** [comment]
is like an anti cheat

2017-01-04 22:53 GMT+01:00 Andrea Pettenuzzo <andreapettenuzzo04@gmail.com>:

**Comment by PetteRed65** [comment]
Can you help me?


Il giovedì 5 gennaio 2017, Andrea Pettenuzzo <andreapettenuzzo04@gmail.com>
ha scritto:

**Comment by alchemistmatt** [comment]
Sorry, I don't know what the issue is.  Check all of the options in the config GUI (`/mg edit MyCTF`)  Also make sure you aren't inside a WorldGuard region with limited allowed commands.

**Comment by Narimm** [comment]
you need to /op yourself to override minigames and worldgaurd

**Comment by PetteRed65** [comment]
i am opped

Il 17/gen/2017 15:15, "Narimm" <notifications@github.com> ha scritto:

**Comment by Narimm** [comment]
Unless you can produce an error/ stack trace that exposes the underlying issue as a programmatic one -  I can only assume this is a configuration issue.  We don't provide configuration support for this plugin.

If you post your config files etc on this thread people might help you

https://www.spigotmc.org/threads/minigames.129414/page-3

**Comment by Narimm** [comment]
We dont provide configuration support via the Github Issues pages.  This is for bug reports.

Support for this can be obtained from the user base on the [Spigot discussion list ](https://www.spigotmc.org/threads/minigames.129414/)or by reading the wiki.

[mgwiki.addstar.com.au](http://mgwiki.addstar.com.au)

Sincerely 
Narimm
AddstarMC
