### ISSUE TITLE
Keep 1.8 compatibility

### ISSUE THREAD

**Issue by Erwanserveur** [AddstarMC/Minigames#77]
Hello i'm use your plugin for my server 1.8 but your last build fix bug of minigame region but in 1.8 the last build cause bug with /mgm edit <game>. Please keep a 1.8 compatibility

[13:25:45] [Server thread/INFO]: Erwan_serveur issued server command: /mgm edit test
[13:25:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mgm' in plugin Minigames v1.11.0-SNAPSHOT-168
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at au.com.mineauz.minigames.menu.Menu.displayMenu(Menu.java:165) ~[?:?]
	at au.com.mineauz.minigames.minigame.Minigame.displayMenu(Minigame.java:1199) ~[?:?]
	at au.com.mineauz.minigames.commands.EditCommand.onCommand(EditCommand.java:62) ~[?:?]
	at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:181) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 15 more

**Comment by Narimm** [comment]
Builds are updated to the latest version of spigot 

At this stage I have no intention of backporting changes to a 1.8 branch....I will discuss with the team however and see where we stand on this
