### ISSUE TITLE
preset spleef causing errors

### ISSUE THREAD

**Issue by cobrasvt1999** [AddstarMC/Minigames#89]
when setting up a spleef arena with spigot 1.11.2 we receive an internal error. This occurs when no other plugins are installed or running on the server. Error is as follows

`[17:17:46] [Server thread/INFO]: cobrasvt1999 issued server command: /mg create spleef
[17:18:05] [Server thread/INFO]: cobrasvt1999 issued server command: /mg set spleef preset spleef
[17:18:05] [Server thread/ERROR]: Cannot load plugins\Minigames\presets\spleef.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 9, column 1:
    	  items:
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at au.com.mineauz.minigames.MinigameSave.reloadFile(MinigameSave.java:41) [Minigames-1.11.0-SNAPSHOT.jar:?]
	at au.com.mineauz.minigames.MinigameSave.<init>(MinigameSave.java:19) [Minigames-1.11.0-SNAPSHOT.jar:?]
	at au.com.mineauz.minigames.presets.PresetLoader.loadPreset(PresetLoader.java:20) [Minigames-1.11.0-SNAPSHOT.jar:?]
	at au.com.mineauz.minigames.commands.set.SetPresetCommand.onCommand(SetPresetCommand.java:63) [Minigames-1.11.0-SNAPSHOT.jar:?]
	at au.com.mineauz.minigames.commands.set.SetCommand.onCommand(SetCommand.java:256) [Minigames-1.11.0-SNAPSHOT.jar:?]
	at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:181) [Minigames-1.11.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 9, column 1:
    	  items:
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	... 25 more
[17:18:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mg' in plugin Minigames v1.11.0-SNAPSHOT-169
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at au.com.mineauz.minigames.presets.PresetLoader.loadPreset(PresetLoader.java:23) ~[?:?]
	at au.com.mineauz.minigames.commands.set.SetPresetCommand.onCommand(SetPresetCommand.java:63) ~[?:?]
	at au.com.mineauz.minigames.commands.set.SetCommand.onCommand(SetCommand.java:256) ~[?:?]
	at au.com.mineauz.minigames.commands.CommandDispatcher.onCommand(CommandDispatcher.java:181) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	... 15 more`

**Comment by Narimm** [comment]
You have used a TAB in a yaml file - its a config error.
```

> org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
> found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
> in 'string', line 9, column 1:

```
