### ISSUE TITLE
Minigames not ending properly on shutdown

### ISSUE THREAD

**Issue by LinsaFTW** [AddstarMC/Minigames#91]
Hey , When server stops / shutdowns in middle of a minigame all the placed and destroyed blocks doesnt regen. No errors on console.

**Comment by LinsaFTW** [comment]
Wait... It left this error before stop:
[03:25:43] [Server thread/INFO]: Minigames successfully disabled.
[03:25:43] [Server thread/ERROR]: Error occurred while disabling Minigames v1.8.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:115) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:98) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
	at au.com.mineauz.minigames.blockRecorder.RecorderData.restoreBlocks(RecorderData.java:355) ~[?:?]
	at au.com.mineauz.minigames.blockRecorder.RecorderData.restoreAll(RecorderData.java:307) ~[?:?]
	at au.com.mineauz.minigames.gametypes.SingleplayerType.quitMinigame(SingleplayerType.java:102) ~[?:?]
	at au.com.mineauz.minigames.PlayerData.quitMinigame(PlayerData.java:475) ~[?:?]
	at au.com.mineauz.minigames.Minigames.onDisable(Minigames.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [Spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [Spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460) [Spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593) [Spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by Narimm** [comment]
Please run the latest version and reopen this if you still get the error . Invalid as your running an older version
